version: '3.1'
services:
  node-swagger-example:
    container_name: node-swagger-example
    build: .
    image: node-swagger-example/todo
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/root/app
      - ./db:/root/db
    links:
      - mysql
    command: sh -c "../db/wait-for-it.sh mysql:3306 && yarn run dev"
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - node-swagger-example-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    command: --default-authentication-plugin=mysql_native_password
volumes:
  node-swagger-example-data:
    external: true
