version: '3.7'
services:
  init:
    container_name: db-init
    build: .
    restart: always
    volumes:
      - ../../db:/db
    links:
      - mysql
    command: bash -c "./db/init/bash-wait-for-it.sh mysql:3306 -t 30 && ./db/init/init.sh"
    
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - node-swagger-example-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    command: --default-authentication-plugin=mysql_native_password
volumes:
  node-swagger-example-data:
    external: true
